export enum Permission {
  USERS_VIEW = 'USERS_VIEW',
  USERS_MANAGE = 'USERS_MANAGE',
  AVAILABILITY_MANAGE_SELF = 'AVAILABILITY_MANAGE_SELF',
  SHIFT_CREATE = 'SHIFT_CREATE',
  SHIFT_ASSIGN = 'SHIFT_ASSIGN',
  SHIFT_PUBLISH = 'SHIFT_PUBLISH',
  SETTINGS_MANAGE = 'SETTINGS_MANAGE',
  OPERATIONS_MANAGE = 'OPERATIONS_MANAGE',
  SWAP_CREATE = 'SWAP_CREATE',
  SWAP_RESPOND = 'SWAP_RESPOND',
  SWAP_CANCEL = 'SWAP_CANCEL',
  SWAP_REVIEW = 'SWAP_REVIEW',
}
