import type { Metadata } from "next";
import "./globals.css";
import AppToaster from "../components/ui/AppToaster";
import ReactQueryProvider from "../components/providers/ReactQueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-full antialiased"
    >
      <body className="min-h-full flex flex-col">
        <ReactQueryProvider>
          {children}
          <AppToaster />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
